library manager;
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'dart:async';
import 'package:rxdart/rxdart.dart';
import 'package:provider/provider.dart';
export 'package:manager/manager.dart' show Manager;
part 'src/models/managerModel.dart';
part 'src/models/task.dart';
part 'src/widgets/managerBuilder.dart';
part 'src/models/paginatedManager.dart';
part 'src/widgets/paginatedCollectionBuilder.dart';
part 'src/models/managerState.dart';
part 'src/models/managerObserverMixin.dart';
const _kPaginatedTaskKey = 'pagino';